### ISSUE TITLE
Can we reconsider the name Dash-chat-2?

### ISSUE THREAD

**Issue by leeyisoft** [molteo-engineering-team/Dash-Chat-2#12]
Can we reconsider the name Dash-chat-2?
Like chat-ui dash-chat-ui dash-ui im-ui or something better?

Dash-Chat-2 这个名称能否再斟酌一下呢？
比如： chat-ui dash-chat-ui dash-ui im-ui 或者其他的更好的名称？

**Comment by SebastienBtr** [comment]
Changing the package name would require doing a new listing on pub.dev, which is not ideal for the apps that are already using this package
