### ISSUE TITLE
Cache Network image plugin throws compile time errors

### ISSUE THREAD

**Issue by naasir27** [molteo-engineering-team/Dash-Chat-2#14]
After integrating dash chat 2 and firebase I am facing this error message on my terminal 
when do flutter run. Which was not available previously.
I noticed that cached_network_image-3.2.0 is only from dash_chat_2

../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/
lib/src/image_provider/multi_image_stream_completer.dart:152:22: Warning:
Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes
null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('../../sdk/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.scheduleFrameCallback(_handleAppFrame);
                     ^
../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/
lib/src/image_provider/cached_network_image_provider.dart:109:29: Warning:
Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes
null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart'
 ('../../sdk/flutter/packages/flutter/lib/src/painting/binding.dart').
      () => PaintingBinding.instance?.imageCache?.evict(key),

can you provide any assistance to resolve this
**Environment**

 - OS: [IOS, ANdroid]
 - Device: [ iPhone13 (IOS 15.5), Pixel 4a (Android 13)] | Emulator
 - Flutter: [2.10.4]
 - Xcode [latest]

**Comment by SebastienBtr** [comment]
Seems like you're sending null in an image ChatMedia url, can you provide a minimal reproducible example?

**Comment by Jackson-Antunes-Sampaio** [comment]
same problem.
 Dart 2.16.2 • DevTools 2.9.2

**Comment by SebastienBtr** [comment]
Closing this as I have not been able to reproduce it and the author didn't give more information
