### ISSUE TITLE
[Bug] Doesn't respond to observable value changes

### ISSUE THREAD

**Issue by ScottWallace** [molteo-engineering-team/Dash-Chat-2#20]
The DashChat widget doesn't reflect changes to observable values in a [GetXController](https://pub.dev/packages/get). In my instance, I'm using a settings controller to set `MessageOptions.currentUserContainerColor` and `MessageOptions.currentUserTextColor`. When I toggle between light and dark mode, other elements wrapped by an `Obx(() =>` on the same page respond to this value change, but the DashChat doesn't.

```
   body: Obx(
          () => DashChat(
            messageOptions: MessageOptions(
                showCurrentUserAvatar: true,
                currentUserContainerColor:
                    _settingsController.currentListTheme.value.offsetColor,
                currentUserTextColor:
                    _settingsController.currentListTheme.value.textColor),
            currentUser: user,
            onSend: (ChatMessage m) {
              setState(() {
                messages.insert(0, m);
              });
            },
            messages: messages,
          ),
        ), 
```

1. Put DashChat on a widget page within a scaffold,
2. Create a GetxController, and observable values for colors and apply them to DashChat,
3. Make the controller's color values respond to light/dark mode changes,
4. Toggle between light and dark mode,
5. Notice that the colors do not change.

**Expected behavior**

It is expected that DashChat will respond to observable value changes.

**Environment**

 - OS: macOS 12.4
 - Device: iOS Simulator
 - Language Version: Channel stable, 3.0.4
 - Software/library Version: DashChat ^0.0.10

**Additional context**

Great product, just need this.

**Comment by SebastienBtr** [comment]
Hey, I never used GetX (and don't want to but that's another debate aha), not sure why it wouldn't work. If you can provide a project for me to test and debug I'll take a look

**Comment by ScottWallace** [comment]
Thanks, I would provide a project, but I've had to move on to a more fully developed package. I'll check in on yours later to check your progress - I prefer this one.
