### ISSUE TITLE
[Question] What is improved from dash_chat (v1)?

### ISSUE THREAD

**Issue by tobiasht** [molteo-engineering-team/Dash-Chat-2#23]
I am guessing this package is related to https://pub.dev/packages/dash_chat, but i do not know what is the difference between the two. Is this an enhancement of the original package or a completely new package with a lot of the same features?

If this package is suppose to be Dashchat´s v2 update, can you please update the documentation on the dash_chat package to reflect this, with a link to the new package? Also a small text with the reason of the new package name would be nice.

**Comment by SebastienBtr** [comment]
Hey, you can see in the readme here: https://github.com/fayeed/dash_chat the link to this new package, and here the discussion about it: https://github.com/fayeed/dash_chat/issues/127

The package has been rewritten entirely and https://pub.dev/packages/dash_chat shouldn't be used anymore as it has a lot of issues and is not maintained

**Comment by tobiasht** [comment]
Oh, so there is a newer readme on GitHub. Can you please update it on [pub.dev](https://pub.dev/packages/dash_chat) too? At the moment it looks like the message is referring to a 2.0.0 release of the same package and since it hasn´t been updated in over a year it seems like it is deprecated.

**Comment by SebastienBtr** [comment]
Yes I asked @fayeed if he could do it 👍 I don't have permission to do it
