### ISSUE TITLE
[Bug] Mention User Overlay doesn't dismiss properly and stays on every screen sometimes.

### ISSUE THREAD

**Issue by Noob-2-pro** [molteo-engineering-team/Dash-Chat-2#26]
I was checking out the example app provider by the team and when I try mentions feature there is unexpected behaviour from the overlay, it doesn't get closed properly ans stays through every screen.

It works fine when :
1. If I select any name from the list
2. If I type @abc then continue typing.

Fails when: 
1. type @absc and press backspace , then overlay don't get dismised and there's this issue as in screenshot.
2. unexpectedly sometimes when writing mentioning names not in list or even names from the list (see video for ref )

**To Reproduce**

1. Compile example app.
3. go to mentions page 
4. type @anyName not in user list and dismiss keyboard without inputting any other character.
or 
@(any name not in list or even from list and then continue typing) , try multiple times (see the attached video for ref)

**Expected behavior**
Overlay should get dismissed when keyboard is dismissed and when no user is selected from the list typing is going on.

**Screenshots**
<img width="1512" alt="Screenshot 2022-09-15 at 6 23 56 PM" src="https://user-images.githubusercontent.com/61776980/190409569-8e2d3adc-745f-4b10-ac30-09746947d31f.png">
<img width="1512" alt="Screenshot 2022-09-15 at 6 23 34 PM" src="https://user-images.githubusercontent.com/61776980/190409595-d332d4a1-ab00-4bdd-b061-12979688ff3c.png">

simulator screens 
![WhatsApp Image 2022-09-14 at 5 46 50 PM](https://user-images.githubusercontent.com/61776980/190410656-e0571eab-32d3-4e35-973c-2fda040366b5.jpeg)

This happened a lot while testing (sometimes it happens and sometimes not)

https://user-images.githubusercontent.com/61776980/190411386-f4fe0dd5-4797-4725-96b6-7ced300b574a.mp4

**Environment**

 - OS: [e.g. Mac m1 pro 2021]
 - Device: [e.g. moto edge 20 fusion] | Emulator - pixel 4 a API 31
 - Language Version: [e.g 3.3.0]
 - Software/library Version [dash_chat_2 0.0.14]

**Additional context**

Suggestion - on mention callback should be called when trigger character is typed, so that we can show all user list.

**Comment by SebastienBtr** [comment]
I could not exactly reproduce it but I improved multiple things and pushed it to the main branch, can you try again using the `main` branch and let me know if it solved the issue?
