### ISSUE TITLE
[Bug] - strange behavior with video messages

### ISSUE THREAD

**Issue by udcode** [molteo-engineering-team/Dash-Chat-2#27]
As you can see in the attached video, when i'm sending 2 videos one after another it behave's strangely, it doesn't happen with photos and regular text 

https://user-images.githubusercontent.com/21666953/190623982-12bb8a78-2f0c-416f-93d5-7e0192326c27.mp4

**Comment by udcode** [comment]
update!
i was able to reproduce the bug in the example project
as you can see in the attached video

https://user-images.githubusercontent.com/21666953/190871749-03988647-1f99-4547-a724-c517b56ecd8f.mov

**Comment by SebastienBtr** [comment]
> update! i was able to reproduce the bug in the example project as you can see in the attached video
> 
>  Screen.Recording.2022-09-17.at.21.34.43.mov 
> the following is the add video button
> 
> ` [ IconButton( icon: Icon(Icons.attach_file), onPressed: () async { FilePickerResult? result = await FilePicker.platform.pickFiles( allowedExtensions: [ 'jpg', 'png', 'jpeg', 'mov', 'mp4', ], allowMultiple: true, allowCompression: true, withData: true, withReadStream: true, type: FileType.custom, );
> 
> ```
>             if (result != null) {
>               List<ChatMessage> newMessages = result.files.map((file) {
>                 return ChatMessage(
>                   user: user,
>                   text: file.name,
>                   medias: [
>                     ChatMedia(
>                       fileName: file.name,
>                       type:
>                           file.extension == 'mov' || file.extension == 'mp4'
>                               ? MediaType.video
>                               : MediaType.image,
>                       url: file.path!,
>                     ),
>                   ],
>                   createdAt: DateTime.now(),
>                 );
>               }).toList();
> 
>               setState(() {
>                 messages.insertAll(0, newMessages);
>               });
>             }
>           },
>         ),
> ]
> ```
> 
> `

Can you give me the full code of media.dart that you're using please?

**Comment by udcode** [comment]
> 

What do you mean by media.dart
(BTW, huge thanks for this incredible package)

**Comment by udcode** [comment]
```

import 'package:dash_chat_2/dash_chat_2.dart';
import 'package:examples/data.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

class Media extends StatefulWidget {
  @override
  _MediaState createState() => _MediaState();
}


class _MediaState extends State<Media> {
  List<ChatMessage> messages = media;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Media example'),
      ),
      body: DashChat(
        currentUser: user,
        inputOptions: InputOptions(
          leading: [
            IconButton(
              icon: Icon(Icons.camera_alt),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(Icons.attach_file),
              onPressed: () async {
                FilePickerResult? result = await FilePicker.platform.pickFiles(
                  allowedExtensions: [
                    'jpg',
                    'png',
                    'jpeg',
                    'mov',
                    'mp4',
                  ],
                  allowMultiple: true,
                  allowCompression: true,
                  withData: true,
                  withReadStream: true,
                  type: FileType.custom,
                );

                if (result != null) {
                  List<ChatMessage> newMessages = result.files.map((file) {
                    return ChatMessage(
                      user: user,
                      text: file.name,
                      medias: [
                        ChatMedia(
                          fileName: file.name,
                          type:
                              file.extension == 'mov' || file.extension == 'mp4'
                                  ? MediaType.video
                                  : MediaType.image,
                          url: file.path!,
                        ),
                      ],
                      createdAt: DateTime.now(),
                    );
                  }).toList();

                  setState(() {
                    messages.insertAll(0, newMessages);
                  });
                }
              },
            ),
          ],
          sendOnEnter: true,
        ),
        onSend: (ChatMessage m) {
          setState(() {
            messages.insert(0, m);
          });
        },
        messages: messages,
      ),
    );
  }
}

```

**Comment by SebastienBtr** [comment]
I was able to reproduce it and it should be fixed, I'll publish a new version

**Comment by Merculiar** [comment]
Seems to me, that after adding a key, and you have more than 2 videos in a row, it always rebuilds videos when scrolling;
Can we somehow handle this?
Attaching recording where I added 1 more video to example data.
Screen Recording 2023-08-31 at 01.17.30
