### ISSUE TITLE
[Question] In this new version is possible to show an input action keyboard below the input field?

### ISSUE THREAD

**Issue by victorc365** [molteo-engineering-team/Dash-Chat-2#36]
Dear developers, 

Thank you very much for your development. I have a question, is it possible in this new version to add an action keyboard below the input field, as it was possible in the previous version with the option inputFooterBuilder? Now I try with chatFooterBuilder, but the options are over the input field is required that this options appears below the input field. 

Thank you for your answer.

**Comment by SebastienBtr** [comment]
Hello, this is not possible at the moment, but a `bottom` param could be added to [InputOptions](https://pub.dev/documentation/dash_chat_2/latest/dash_chat_2/InputOptions-class.html). It would work like [trailing](https://pub.dev/documentation/dash_chat_2/latest/dash_chat_2/InputOptions/trailing.html) and [leading](https://pub.dev/documentation/dash_chat_2/latest/dash_chat_2/InputOptions/leading.html) params
