### ISSUE TITLE
May I ask when will dash chat v2 be released?

### ISSUE THREAD

**Issue by simon-zhangmuye** [molteo-engineering-team/Dash-Chat-2#4]
I mean the stable version.

**Comment by SebastienBtr** [comment]
Hey, progress is on hold at the moment, I wish to have time in 2022 to continue it. I can't give you a date now but contributions and feedback are more than welcome

**Comment by bzark** [comment]
How unstable is v2?  Is there a list of open issues and/or non-implemented features?

**Comment by SebastienBtr** [comment]
I have noticed issues with lazy loading more messages, not sure what the issue is exactly. Otherwise, the non-implemented features are the ones marked as "WIP" in the readme

**Comment by SebastienBtr** [comment]
I just published version 0.0.4, it doesn't include the "WIP" features but should be good to use in production 🎉 
Of course, let me know if you find any issues!

**Comment by SebastienBtr** [comment]
In the future you'll be able to reply to a particular message in a facebook/whatsapp way:

![image](https://user-images.githubusercontent.com/18089010/156582126-3f04515d-cb03-4d7a-aa2b-f3e992b7c1d4.png)

**Comment by ghozay19** [comment]
> In the future you'll be able to reply to a particular message in a facebook/whatsapp way:
> 
> ![image](https://user-images.githubusercontent.com/18089010/156582126-3f04515d-cb03-4d7a-aa2b-f3e992b7c1d4.png)

may i know when we can use this feature?
