### ISSUE TITLE
Does it support  flutter web?

### ISSUE THREAD

**Issue by SatyamKr07** [molteo-engineering-team/Dash-Chat-2#5]
In pub.dev it shows it supports only Android and Ios. So what about the web support?

**Comment by SebastienBtr** [comment]
It doesn't support web because of CachedNetworkImage (https://pub.dev/packages/cached_network_image) and the usage of `File` to load device files line 98 of `media_container.dart`

**Comment by SebastienBtr** [comment]
I added support for web in 0.0.5 🎉
